#ifndef RETHREAD_TEST_HELGRIND_ANNOTATIONS_H
#define RETHREAD_TEST_HELGRIND_ANNOTATIONS_H

#include <valgrind/helgrind.h>

#define _GLIBCXX_SYNCHRONIZATION_HAPPENS_BEFORE(Marker_) ANNOTATE_HAPPENS_BEFORE(Marker_)
#define _GLIBCXX_SYNCHRONIZATION_HAPPENS_AFTER(Marker_) ANNOTATE_HAPPENS_AFTER(Marker_)
#define _GLIBCXX_EXTERN_TEMPLATE -1

#endif
